### ISSUE TITLE
adding proxy list to Auto-Webpage-Login-Password-by-force

### ISSUE THREAD

**Issue by DaveStarbug** [PhilipMur/Auto-Webpage-Login-Password-by-force#1]
Hi Philip. I would like to first Thank for your app that is very useful for me. second i want to add proxy list to app. as you know some login pages after some tries say 'you can try after 5 minutes' or something like that. i want to break this reaction by proxy list. Thanks.

**Comment by PhilipMur** [comment]
Hi DaveStartbug ,I have added support for Proxy to be used and also a way to revert back to normal browsing without a proxy.
Thank you for your kind words , I am glad you found it useful.

PhilipM

**Comment by PhilipMur** [comment]
Hi DaveStartbug , Proxy List added and a few things changed.

**Comment by DaveStarbug** [comment]
Thanks very much.
